2020-08-03 18:17:53,491 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:17:53,521 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:20:20,231 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:20:20,274 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:20:43,720 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:20:43,752 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:21:56,174 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:21:56,197 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:23:22,793 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:23:22,824 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:23:52,220 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:23:52,251 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:23:59,300 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:23:59,301 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-03 18:24:15,260 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:24:15,283 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:24:29,299 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:24:29,325 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:25:31,810 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:25:31,833 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:26:34,237 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:26:34,266 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:27:14,211 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:27:14,231 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:28:04,396 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:28:04,420 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:28:15,502 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:28:15,522 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:28:15,548 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:28:15,576 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:29:02,696 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:29:02,747 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:29:02,808 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:29:02,842 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:29:07,150 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:29:07,163 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:29:07,165 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:30:03,959 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:30:03,979 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:30:04,017 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:30:04,072 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:30:38,692 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:30:38,718 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:30:55,761 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:30:55,787 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:30:58,556 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:30:58,558 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-03 18:31:21,020 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:31:21,042 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:31:34,145 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:31:34,168 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:31:36,794 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:31:36,805 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:31:36,806 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:32:07,013 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:32:07,049 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:32:11,342 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:32:11,348 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:32:11,352 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:33:58,600 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:33:58,629 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:34:02,611 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:34:02,619 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:34:02,621 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:38:35,198 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:38:35,223 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:38:41,086 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:38:41,094 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:38:41,098 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:38:55,404 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:38:55,438 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:39:13,101 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:39:13,123 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:50:06,100 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:50:06,124 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:50:09,896 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:50:09,898 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-03 18:52:33,946 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:52:33,979 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:52:38,816 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:52:38,827 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:52:38,828 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:53:30,338 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:53:30,369 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:53:38,587 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:53:38,592 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:53:38,593 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:54:24,204 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:54:24,236 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:54:29,793 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:54:29,794 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-03 18:54:42,111 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:54:42,145 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:54:45,684 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 18:54:45,692 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:54:45,693 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-03 18:56:18,984 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 18:56:19,018 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 23:45:43,808 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 23:45:43,839 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 23:45:48,904 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 23:45:48,905 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-03 23:47:33,740 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 23:47:33,761 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 23:50:38,911 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 23:50:38,942 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 23:51:27,557 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 23:51:27,586 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-03 23:52:29,522 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-03 23:52:29,555 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:00:25,763 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:00:25,797 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:02:00,493 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:02:00,494 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-04 00:02:32,474 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:02:32,496 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:02:32,500 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:02:32,501 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-04 00:02:53,866 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:02:53,907 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:02:53,909 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:02:53,910 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-04 00:03:52,959 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:03:52,998 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:03:53,004 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:03:53,005 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-04 00:03:53,074 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:03:53,110 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:03:53,114 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:03:53,115 - ERROR - decorators:wrapper:37 - ()- MainThread - ERROR NAME: [Errno 111] Connection refused !!!
Traceback (most recent call last):
  File "/home/device/Рабочий стол/Databases and PyQT/common/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "client.py", line 28, in __init__
    self.client_socket.connect(args_validation(addr, port))
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-04 00:04:50,838 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:04:50,849 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:04:50,902 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:04:50,903 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:04:50,904 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:04:50,905 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:05:11,223 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:05:11,225 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:05:15,608 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:05:15,609 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:08:40,772 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:08:40,806 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:08:40,867 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:08:40,904 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:08:48,530 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:08:48,538 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:08:48,539 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:08:53,542 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:08:53,548 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:08:53,551 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:11:52,625 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:11:52,670 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:11:52,694 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:class Client(metaclass=ClientVerifier): !!!
2020-08-04 00:11:52,731 - INFO - decorators:wrapper:31 - ()- MainThread - The "__init__" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:12:20,815 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:12:20,819 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:12:20,821 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:12:23,846 - INFO - decorators:wrapper:31 - ()- MainThread - The "args_validation" function is called from the module -> client.py -> function:client = Client(addr, port) !!!
2020-08-04 00:12:23,852 - INFO - decorators:wrapper:31 - ()- Thread-1 - The "send_message" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
2020-08-04 00:12:23,854 - INFO - decorators:wrapper:31 - ()- Thread-2 - The "receive" function is called from the module -> /home/device/.pyenv/versions/3.7.0/lib/python3.7/threading.py -> function:self._bootstrap_inner() !!!
